# Generated by Django 5.1.4 on 2024-12-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=100, verbose_name='Товар')),
                ('description', models.CharField(help_text='Введите описание товара', max_length=500, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену товара', max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.IntegerField(verbose_name='Кол-во товара')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Итоговая стоимость товара', max_digits=10, verbose_name='Итоговая стоимость')),
                ('category', models.CharField(choices=[('Сосиски', 'Сосиски'), ('Колбаса', 'Колбаса'), ('Яблоки', 'Яблоки'), ('Киви', 'Киви'), ('Виноград', 'Виноград')], max_length=50, verbose_name='Категория товара')),
                ('date_of_receipt', models.DateField(blank=True, help_text='Введите дату добавления', null=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
